project:
  type: website
  output-dir: docs

website:
  title: "Data And Power Simulations"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: scripts/dataAndPowerSimulations_presentation.qmd
        text: Presentation
      - href: scripts/EcoTRACEPowerAnalysis_report.qmd
        text: Power Analysis EcoTRACE
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

