project:
  type: website
  output-dir: docs
  resources: images/*

website:
  title: "Data & Power Sims"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: presentation.qmd
        text: Presentation
      - href: handsOnSimulation.qmd
        text: Hands-On Simulations
      - text: "Example Power Analyses"
        menu: 
        - href: scripts/EcoTRACEPowerAnalysis_report.qmd
          text: Power Analysis EcoTRACE
        - href: scripts/CETEyeTrackingPowerAnalysis_report.qmd
          text: Power Analysis CET Eye-Tracking
    right:
      - icon: github
        href: "https://github.com/EGuizarRosales/DataAndPowerSimulations"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

